### ISSUE TITLE
Doesn't work if there is a comment on same line

### ISSUE THREAD

**Issue by mizterp** [cmgddd/Brackets-css-color-preview#15]
Just realized that the following doesn't show the colors:

``` css
.CodeMirror .cm-atom{color: #6897BB;} /*Atribbute value ex. #f00 in color:#f00;*/
.CodeMirror .cm-def{color: #ffcf85;} /*variable definition*/
```
